korba: /var/www/OpenBSD/site/site63-korba.tgz \
  /var/www/htdocs/korba-install.conf

/var/www/htdocs/korba-install.conf : korba-install.conf
	install -o sysop -g daemon -m 0644 \
	  korba-install.conf /var/www/htdocs/korba-install.conf

